export let background: number[];
export let meshColor: number[];
export let lightColor: number[];
export let lightDirection: number[];
export let lightPosition: number[];
export let ambientLightAmount: number;
export let diffuseLightAmount: number;
export let specularLightAmount: number;
export let materialShininess: number;
