export function main(params: any): any[][];
export function getParameterDefinitions(): ({
    name: string;
    type: string;
    caption: string;
    checked?: undefined;
    initial?: undefined;
    min?: undefined;
    max?: undefined;
    step?: undefined;
    size?: undefined;
    maxLength?: undefined;
    placeholder?: undefined;
} | {
    name: string;
    type: string;
    checked: boolean;
    initial: string;
    caption: string;
    min?: undefined;
    max?: undefined;
    step?: undefined;
    size?: undefined;
    maxLength?: undefined;
    placeholder?: undefined;
} | {
    name: string;
    type: string;
    initial: string;
    caption: string;
    checked?: undefined;
    min?: undefined;
    max?: undefined;
    step?: undefined;
    size?: undefined;
    maxLength?: undefined;
    placeholder?: undefined;
} | {
    name: string;
    type: string;
    initial: number;
    min: number;
    max: number;
    step: number;
    caption: string;
    checked?: undefined;
    size?: undefined;
    maxLength?: undefined;
    placeholder?: undefined;
} | {
    name: string;
    type: string;
    initial: string;
    size: number;
    maxLength: number;
    caption: string;
    placeholder: string;
    checked?: undefined;
    min?: undefined;
    max?: undefined;
    step?: undefined;
} | {
    name: string;
    type: string;
    initial: string;
    min: string;
    max: string;
    caption: string;
    placeholder: string;
    checked?: undefined;
    step?: undefined;
    size?: undefined;
    maxLength?: undefined;
})[];
